### ISSUE TITLE
Error: The maximum line length of 80 characters is exceeded.

### ISSUE THREAD

**Issue by gomex** [GsActions/commit-message-checker#11]
I am running the same workflows for push and pull_request. The push is running well, but the pull_request is falling:

https://github.com/TotalCross/totalcross/pull/117/checks?check_run_id=1000747757

**Comment by gilbertsoft** [comment]
Your desciption is indeed longer than the 72 characters so the fail seems correct here. Because the description is taken from the PR description and not included in the commit itself the push check does not fail. Have a deeper look at the messages which are printed on the check in the log to see the difference.
The question is now what exactly do you expect, if you don't like to have the description of the PR checked you should work with two separated workflows instead.
Currently there is no option to disable the description check of a PR but maybe you wanna make a feature request for this...

**Comment by gilbertsoft** [comment]
BTW here is the related part which concats the title and the body of the PR https://github.com/GsActions/commit-message-checker/blob/master/src/input-helper.ts#L66-L68

**Comment by otavio** [comment]
Indeed, an option to disable the PR check would be good as in this case we need is to check the commit messages /when/ a contributor sends a PR.

**Comment by gilbertsoft** [comment]
Will close this one in favor of #12
